# This is a cron job that refreshes the mongodb so it doesn't pause

name: DB-Refresh

# Controls when the workflow will run
on:
  schedule:
  - cron: '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Run a one-line script
        run: curl https://www.mygreenearth.org/api/dbRefresh
